const fs = require('fs');

const alunos = `import React, { useState } from 'react';\nimport api from '../utils/api';\n\nconst Alunos: React.FC = () => {\n  const [lista, setLista] = useState<any[]>([]);\n  const [carregando, setCarregando] = useState(false);\n\n  const carregar = async () => {\n    setCarregando(true);\n    try {\n      const response = await api.get('/alunos');\n      setLista(response.data);\n    } catch (e) {\n      console.error(e);\n    } finally {\n      setCarregando(false);\n    }\n  };\n\n  React.useEffect(() => { carregar(); }, []);\n\n  return (\n    <div className="p-6">\n      <h1 className="text-2xl font-bold mb-4">Alunos</h1>\n      {carregando && <p className="text-sm text-gray-500">Carregando...</p>}\n      <ul className="space-y-2">\n        {lista.map((a) => (\n          <li key={a.id} className="border rounded p-3">\n            <p className="font-medium">{a.nome}</p>\n            <p className="text-xs text-gray-500">{a.turma_id || 'Sem turma'}</p>\n          </li>\n        ))}\n      </ul>\n    </div>\n  );\n};\n\nexport default Alunos;\n`;

const turmas = `import React, { useState } from 'react';\nimport api from '../utils/api';\n\nconst Turmas: React.FC = () => {\n  const [lista, setLista] = useState<any[]>([]);\n  const [carregando, setCarregando] = useState(false);\n\n  const carregar = async () => {\n    setCarregando(true);\n    try {\n      const response = await api.get('/turmas');\n      setLista(response.data);\n    } catch (e) {\n      console.error(e);\n    } finally {\n      setCarregando(false);\n    }\n  };\n\n  React.useEffect(() => { carregar(); }, []);\n\n  return (\n    <div className="p-6">\n      <h1 className="text-2xl font-bold mb-4">Turmas</h1>\n      {carregando && <p className="text-sm text-gray-500">Carregando...</p>}\n      <ul className="space-y-2">\n        {lista.map((t) => (\n          <li key={t.id} className="border rounded p-3">\n            <p className="font-medium">{t.label}</p>\n            <p className="text-xs text-gray-500">{t.horario} {t.nivel || ''}</p>\n          </li>\n        ))}\n      </ul>\n    </div>\n  );\n};\n\nexport default Turmas;\n`;

fs.writeFileSync('C:/Users/HP/fiz-app/frontend/src/pages/Alunos.tsx', alunos);
fs.writeFileSync('C:/Users/HP/fiz-app/frontend/src/pages/Turmas.tsx', turmas);
console.log('Paginas Alunos e Turmas criadas');
